import { Content } from "@radix-ui/react-accordion";
import OneImg from "../assets/one.jpg";
import TwoImg from "../assets/two.jpg";
import ThreeImg from "../assets/three.jpg";
import FourImg from "../assets/four.jpg";
import Profile1 from "../assets/profile1.jpg";
import Profile2 from "../assets/profile2.jpg";
import Profile3 from "../assets/profile3.avif";
import Profile4 from "../assets/profile4.avif";

const PREMIUM_HOUSES = [
  {
    url: OneImg,
    beds: "5 Bedrooms",
    bathroom: "2 Bathroom",
    title: "The Pinnacle at Highland Park",
    amount: "$3,56798.00",
    address: "123 Maple Street, New York",
  },
  {
    url: TwoImg,
    beds: "5 Bedrooms",
    bathroom: "2 Bathroom",
    title: "The Pinnacle at Highland Park",
    amount: "$2,56798.00",
    address: "123 Maple Street, New York",
  },
  {
    url: ThreeImg,
    beds: "5 Bedrooms",
    bathroom: "2 Bathroom",
    title: "The Pinnacle at Highland Park",
    amount: "$4,56798.00",
    address: "123 Maple Street, New York",
  },
  {
    url: FourImg,
    beds: "5 Bedrooms",
    bathroom: "2 Bathroom",
    title: "The Pinnacle at Highland Park",
    amount: "$5,56798.00",
    address: "123 Maple Street, New York",
  },
  {
    url: OneImg,
    beds: "5 Bedrooms",
    bathroom: "2 Bathroom",
    title: "The Pinnacle at Highland Park",
    amount: "$2,56798.00",
    address: "123 Maple Street, New York",
  },
  {
    url: TwoImg,
    beds: "5 Bedrooms",
    bathroom: "2 Bathroom",
    title: "The Pinnacle at Highland Park",
    amount: "$3,56798.00",
    address: "123 Maple Street, New York",
  },
];

const FAQ_LIST = [
  {
    title: "Do you assist with property financing?",
    Content:
      "We work closely with reputable financial institutions to help you secure the best financing options available. Our team guides you through pre-approval, explains various loan types, and ensures you receive personalized financial advice. We make the mortgage process smooth and stress-free, enabling you to focus on finding your ideal property.",
    url: "src/assets/one.jpg",
  },
  {
    title: "What areas do you serve?",
    Content:
      "Our services cover a wide range of locations including metropolitan cities, suburban neighborhoods, and scenic rural regions. Whether you're looking for a vibrant urban lifestyle or peaceful countryside living, we help you find the perfect location that aligns with your lifestyle and investment goals.",
    url: "src/assets/two.jpg",
  },
  {
    title: "Do you offer investment property options?",
    Content:
      "Yes, we provide expert guidance for clients interested in real estate investment. From multi-family homes to commercial units, we help you identify high-return opportunities. Our insights into market trends and rental yields ensure your investment decisions are well-informed and profitable.",
    url: "src/assets/three.jpg",
  },
  {
    title: "Can you help first-time homebuyers?",
    Content:
      "Absolutely! We take special care of first-time buyers by offering step-by-step support throughout the buying process. From understanding the market to handling paperwork and financing, we make sure you're confident and comfortable with every decision. Our goal is to make your first purchase memorable and stress-free.",
    url: "src/assets/four.jpg",
  },
  {
    title: "Do you provide relocation services?",
    Content:
      "Yes, we offer comprehensive relocation assistance for individuals and families moving to new cities or countries. Our services include area orientation, school recommendations, temporary housing, and settling-in support. We help you transition smoothly and start your new chapter with ease.",
    url: "src/assets/five.jpg",
  },
];

const CLIENTS = [
  {
    avatar: Profile1,
    name: "Sajibur Rahman",
    role: "UI/UX Designer",
    review:
      "Working with this team was a pleasure. They understood our vision and helped us find property that exceeded our expectations. We couldn't have done it without them!",
  },
  {
    avatar: Profile2,
    name: "Sajibur Rahman",
    role: "UI/UX Designer",
    review:
      "Working with this team was a pleasure. They understood our vision and helped us find property that exceeded our expectations. We couldn't have done it without them!",
  },
  {
    avatar: Profile3,
    name: "Sajibur Rahman",
    role: "UI/UX Designer",
    review:
      "Working with this team was a pleasure. They understood our vision and helped us find property that exceeded our expectations. We couldn't have done it without them!",
  },
  {
    avatar: Profile4,
    name: "Sajibur Rahman",
    role: "UI/UX Designer",
    review:
      "Working with this team was a pleasure. They understood our vision and helped us find property that exceeded our expectations. We couldn't have done it without them!",
  },
];

const PROP_LIST = [
  {
    url: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Pinnacle at Highland Park",
    type: "House",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$4,56798.00",
    address: "123 Maple Street, New York",
  },
  {
    url: "https://images.pexels.com/photos/164558/pexels-photo-164558.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Sunset View Villas",
    type: "Villa",
    beds: "4 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$789,000.00",
    address: "456 Ocean Drive, Miami",
  },
  {
    url: "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Urban Nest Loft",
    type: "Apartment",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$325,400.00",
    address: "789 Skyline Blvd, San Francisco",
  },
  {
    url: "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Lakeside Serenity",
    type: "House",
    beds: "5 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$1,050,000.00",
    address: "321 Lakeview Lane, Chicago",
  },
  {
    url: "https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Mountain Crest Retreat",
    type: "Cabin",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$620,500.00",
    address: "654 Forest Trail, Denver",
  },
  {
    url: "https://images.pexels.com/photos/221540/pexels-photo-221540.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Garden Estate",
    type: "Villa",
    beds: "6 Bedrooms",
    bathrooms: "5 Bathroom",
    price: "$1,850,000.00",
    address: "987 Blossom Street, Los Angeles",
  },
  {
    url: "https://images.pexels.com/photos/277667/pexels-photo-277667.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Palm Grove Residence",
    type: "House",
    beds: "4 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$799,999.00",
    address: "321 Palm Avenue, Tampa",
  },
  {
    url: "https://images.pexels.com/photos/209315/pexels-photo-209315.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Downtown Chic Condo",
    type: "Condo",
    beds: "1 Bedroom",
    bathrooms: "1 Bathroom",
    price: "$210,000.00",
    address: "1600 Main Street, Boston",
  },
  {
    url: "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Evergreen Hills Manor",
    type: "Mansion",
    beds: "7 Bedrooms",
    bathrooms: "6 Bathroom",
    price: "$2,750,000.00",
    address: "72 Evergreen Rd, Seattle",
  },
  {
    url: "https://images.pexels.com/photos/460695/pexels-photo-460695.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Coastal Breeze Bungalow",
    type: "House",
    beds: "2 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$540,300.00",
    address: "84 Shoreline Blvd, San Diego",
  },
  {
    url: "https://images.pexels.com/photos/164522/pexels-photo-164522.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Pinewood Escape",
    type: "Cabin",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$330,000.00",
    address: "25 Pinewood Way, Aspen",
  },
  {
    url: "https://images.pexels.com/photos/226407/pexels-photo-226407.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Midtown Heights Apartment",
    type: "Apartment",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$455,000.00",
    address: "1001 Midtown Ave, Atlanta",
  },
  {
    url: "https://images.pexels.com/photos/209274/pexels-photo-209274.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Skyline Towers",
    type: "Penthouse",
    beds: "4 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$1,300,000.00",
    address: "2022 Central Park South, New York",
  },
  {
    url: "https://images.pexels.com/photos/1127119/pexels-photo-1127119.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Seaside Cliff House",
    type: "Villa",
    beds: "3 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$980,000.00",
    address: "73 Coastal Cliff Road, Santa Monica",
  },
  {
    url: "https://images.pexels.com/photos/276593/pexels-photo-276593.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Harbor Lights Apartment",
    type: "Apartment",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$375,900.00",
    address: "912 Dockside Dr, Baltimore",
  },
  {
    url: "https://images.pexels.com/photos/534228/pexels-photo-534228.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Rosewood Residence",
    type: "House",
    beds: "4 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$678,500.00",
    address: "187 Rosewood Lane, Dallas",
  },
  {
    url: "https://images.pexels.com/photos/280216/pexels-photo-280216.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Artisan Flat",
    type: "Studio",
    beds: "1 Bedroom",
    bathrooms: "1 Bathroom",
    price: "$185,000.00",
    address: "202 Artists Row, Portland",
  },
  {
    url: "https://images.pexels.com/photos/259646/pexels-photo-259646.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Valley View Cottage",
    type: "Cottage",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$520,000.00",
    address: "512 Valley Trail, Phoenix",
  },
  {
    url: "https://images.pexels.com/photos/259825/pexels-photo-259825.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Willow Creek Townhome",
    type: "Townhouse",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$410,700.00",
    address: "336 Willow Creek Lane, Austin",
  },
  {
    url: "https://images.pexels.com/photos/3555615/pexels-photo-3555615.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Elm Street Classic",
    type: "House",
    beds: "4 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$589,900.00",
    address: "441 Elm Street, Philadelphia",
  },
  ///
  {
    url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Riverside Harmony",
    type: "House",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$645,300.00",
    address: "142 Riverbank Lane, Portland",
  },
  {
    url: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Ivy Loft",
    type: "Loft",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$358,900.00",
    address: "308 Ivy Street, Brooklyn",
  },
  {
    url: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Golden Gate Heights",
    type: "Apartment",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$755,200.00",
    address: "1299 Bayview Dr, San Francisco",
  },
  {
    url: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Cedar Wood Estate",
    type: "Villa",
    beds: "5 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$1,125,000.00",
    address: "95 Cedar Hill Rd, Minneapolis",
  },
  {
    url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Maple Grove Retreat",
    type: "Cottage",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$289,500.00",
    address: "76 Maple Grove, Vermont",
  },
  {
    url: "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Capital View",
    type: "Penthouse",
    beds: "4 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$1,700,000.00",
    address: "600 Constitution Ave, Washington, DC",
  },
  {
    url: "https://images.pexels.com/photos/3935324/pexels-photo-3935324.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Ocean Breeze Homes",
    type: "House",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$688,800.00",
    address: "22 Coastline Blvd, Jacksonville",
  },
  {
    url: "https://images.pexels.com/photos/331692/pexels-photo-331692.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Lakeview Heights",
    type: "House",
    beds: "4 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$888,900.00",
    address: "100 Lakeshore Rd, Madison",
  },
  {
    url: "https://images.pexels.com/photos/259957/pexels-photo-259957.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Desert Bloom Villa",
    type: "Villa",
    beds: "5 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$990,000.00",
    address: "18 Sunset Dunes, Phoenix",
  },
  {
    url: "https://images.pexels.com/photos/460695/pexels-photo-460695.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Skyline Modern Condo",
    type: "Condo",
    beds: "2 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$472,000.00",
    address: "804 Skyline Blvd, Houston",
  },
  {
    url: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Whispering Pines House",
    type: "House",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$564,300.00",
    address: "12 Whisper Pine Rd, Boulder",
  },
  {
    url: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Sunridge Apartment",
    type: "Apartment",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$345,700.00",
    address: "789 Sunridge Ave, Sacramento",
  },
  {
    url: "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Old Town Charmer",
    type: "House",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$399,999.00",
    address: "55 Colonial St, Charleston",
  },
  {
    url: "https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Metro Edge",
    type: "Loft",
    beds: "1 Bedroom",
    bathrooms: "1 Bathroom",
    price: "$278,400.00",
    address: "19 Metro Plaza, Detroit",
  },
  {
    url: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Countryside Haven",
    type: "Cottage",
    beds: "2 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$305,000.00",
    address: "304 Country Lane, Raleigh",
  },
  {
    url: "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "The Horizon Edge",
    type: "Penthouse",
    beds: "3 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$1,280,000.00",
    address: "88 Horizon St, Miami",
  },
  {
    url: "https://images.pexels.com/photos/210557/pexels-photo-210557.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Greenfield Estate",
    type: "House",
    beds: "4 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$677,000.00",
    address: "60 Greenfield Rd, Nashville",
  },
  {
    url: "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Stonebridge Villa",
    type: "Villa",
    beds: "6 Bedrooms",
    bathrooms: "5 Bathroom",
    price: "$1,920,000.00",
    address: "200 Stonebridge Court, San Antonio",
  },
  {
    url: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Hilltop View Residence",
    type: "House",
    beds: "3 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$730,800.00",
    address: "330 Hilltop Blvd, Salt Lake City",
  },
  {
    url: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Amber Lane Cottage",
    type: "Cottage",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$268,500.00",
    address: "88 Amber Lane, Asheville",
  },
  {
    url: "https://images.pexels.com/photos/1105754/pexels-photo-1105754.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Hillside Bungalow",
    type: "Loft",
    beds: "4 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$1,262,582.00",
    address: "400 Urban St, San Francisco",
  },
  {
    url: "https://images.pexels.com/photos/210558/pexels-photo-210558.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Green Acres Villa",
    type: "Loft",
    beds: "2 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$460,955.00",
    address: "300 Timberline Trail, Salt Lake City",
  },
  {
    url: "https://images.pexels.com/photos/731812/pexels-photo-731812.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Sunset Terrace",
    type: "Apartment",
    beds: "3 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$1,250,784.00",
    address: "121 Crystal Bay Blvd, San Diego",
  },
  {
    url: "https://images.pexels.com/photos/2103826/pexels-photo-2103826.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Green Acres Villa",
    type: "Condo",
    beds: "3 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$1,526,147.00",
    address: "180 Golden Rd, Las Vegas",
  },
  {
    url: "https://images.pexels.com/photos/816198/pexels-photo-816198.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Seaside Haven",
    type: "Cottage",
    beds: "1 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$530,892.00",
    address: "65 Terrace Blvd, Phoenix",
  },
  {
    url: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Green Acres Villa",
    type: "Villa",
    beds: "5 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$840,760.00",
    address: "700 Skyview Ave, New York",
  },
  {
    url: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Timberline Retreat",
    type: "Apartment",
    beds: "2 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$1,956,996.00",
    address: "300 Timberline Trail, Salt Lake City",
  },
  {
    url: "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Downtown Dream",
    type: "House",
    beds: "2 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$664,982.00",
    address: "121 Crystal Bay Blvd, San Diego",
  },
  {
    url: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Mountain Peak Villa",
    type: "Villa",
    beds: "1 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$919,366.00",
    address: "99 Green Acres Rd, Houston",
  },
  {
    url: "https://images.pexels.com/photos/2179603/pexels-photo-2179603.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Mountain Peak Villa",
    type: "House",
    beds: "1 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$1,017,003.00",
    address: "300 Timberline Trail, Salt Lake City",
  },
  {
    url: "https://images.pexels.com/photos/208321/pexels-photo-208321.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Rustic Forest Cabin",
    type: "House",
    beds: "4 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$935,487.00",
    address: "600 City Center Blvd, Seattle",
  },
  {
    url: "https://images.pexels.com/photos/2962124/pexels-photo-2962124.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Rustic Forest Cabin",
    type: "House",
    beds: "1 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$1,176,246.00",
    address: "700 Skyview Ave, New York",
  },
  {
    url: "https://images.pexels.com/photos/2146548/pexels-photo-2146548.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "City Lights Apartment",
    type: "Condo",
    beds: "2 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$1,133,292.00",
    address: "75 Hillside Dr, Boulder",
  },
  {
    url: "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "City Lights Apartment",
    type: "Cottage",
    beds: "4 Bedrooms",
    bathrooms: "2 Bathroom",
    price: "$637,890.00",
    address: "90 Lakefront Ave, Chicago",
  },
  {
    url: "https://images.pexels.com/photos/3935344/pexels-photo-3935344.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Lakeside Retreat",
    type: "Condo",
    beds: "1 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$1,385,810.00",
    address: "89 Maple St, Boston",
  },
  {
    url: "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Hillside Bungalow",
    type: "Penthouse",
    beds: "1 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$1,010,206.00",
    address: "101 Elm St, Dallas",
  },
  {
    url: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Maplewood Mansion",
    type: "Villa",
    beds: "5 Bedrooms",
    bathrooms: "3 Bathroom",
    price: "$781,015.00",
    address: "65 Terrace Blvd, Phoenix",
  },
  {
    url: "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Riverstone Estate",
    type: "House",
    beds: "4 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$656,091.00",
    address: "320 Downtown St, Austin",
  },
  {
    url: "https://images.pexels.com/photos/259580/pexels-photo-259580.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Seaside Haven",
    type: "Villa",
    beds: "1 Bedrooms",
    bathrooms: "1 Bathroom",
    price: "$1,117,265.00",
    address: "180 Golden Rd, Las Vegas",
  },
  {
    url: "https://images.pexels.com/photos/3935324/pexels-photo-3935324.jpeg?auto=compress&cs=tinysrgb&w=1200",
    title: "Rustic Forest Cabin",
    type: "Loft",
    beds: "2 Bedrooms",
    bathrooms: "4 Bathroom",
    price: "$1,481,549.00",
    address: "65 Terrace Blvd, Phoenix",
  },
];

export { PREMIUM_HOUSES, FAQ_LIST, CLIENTS, PROP_LIST };
